"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, CalendarDays, Wrench } from "lucide-react";
import { PublicPageShell } from "@/components/public/public-page-shell";

function SectionHeading({ children }: { children: React.ReactNode }) {
  return <div className="mb-6"><h2 className="suzuki-condensed text-3xl font-bold uppercase text-[#171717]">{children}</h2><div className="mt-3 flex w-20 gap-1"><span className="h-[3px] flex-1 bg-[#003b92]" /><span className="h-[3px] w-7 bg-[#ed1b2f]" /></div></div>;
}

export default function AboutDealerPage() {
  return <PublicPageShell>
    <section className="relative h-40 overflow-hidden bg-[#172c48] md:h-52">
      <img src="/suzuki/banners/test-drive.jpg" alt="Suzuki Vinh" className="absolute inset-0 h-full w-full object-cover opacity-45" />
      <div className="relative mx-auto flex h-full max-w-[1400px] flex-col items-center justify-center px-5 text-white"><h1 className="suzuki-condensed text-3xl font-bold uppercase">Về đại lý</h1><div className="mt-3 flex w-14 gap-1"><span className="h-[3px] flex-1 bg-white" /><span className="h-[3px] w-5 bg-[#ed1b2f]" /></div><p className="mt-3 text-sm">Trang chủ <span className="mx-1">&gt;</span> Về đại lý</p></div>
    </section>
    <main className="mx-auto max-w-[1400px] px-5 py-12 md:py-16">
      <section className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16">
        <div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#003b92]">Suzuki Vinh Nghệ An</p><h2 className="suzuki-condensed mt-3 text-4xl font-bold uppercase leading-tight text-[#171717]">Giới thiệu về Suzuki Vinh</h2><div className="mt-5 flex w-20 gap-1"><span className="h-[3px] flex-1 bg-[#003b92]" /><span className="h-[3px] w-7 bg-[#ed1b2f]" /></div><p className="mt-6 text-lg leading-8 text-slate-700">Suzuki Vinh là Đại lý chính thức của Suzuki Việt Nam tại thành phố Vinh. Chúng tôi cam kết cung cấp xe Suzuki với giá tốt, nhiều chương trình khuyến mãi hấp dẫn và hỗ trợ trả góp đến 80% giá trị xe.</p><Link href="/dang-ky-lai-thu" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#ed1b2f] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#003b92]">Đăng ký lái thử <ArrowRight size={16} /></Link></div>
        <img src="/suzuki/about/showroom.jpg" alt="Mặt tiền Suzuki Vinh" className="min-h-72 w-full rounded-xl object-cover shadow-md" />
      </section>
      <section className="mt-16 grid gap-10 border-t border-slate-200 pt-14 lg:grid-cols-[1.1fr_.9fr]"><div><SectionHeading>1. Giới thiệu về Suzuki Vinh</SectionHeading><div className="space-y-5 leading-8 text-slate-700"><p>Công ty TNHH Việt Pháp (Suzuki Vinh) được hình thành và chính thức đi vào hoạt động ngày 17/12/2013, là đại lý ủy quyền chính thức của Suzuki Việt Nam tại khu vực Miền Trung.</p><p>Suzuki Vinh được xây dựng đạt chuẩn đại lý Premium vào tháng 12/2018. Từ đầu năm 2013, công ty mở rộng kinh doanh các sản phẩm ô tô Nhật Bản và được Suzuki Việt Nam lựa chọn làm đối tác chiến lược, định hướng phát triển hệ thống đại lý ô tô đạt tiêu chuẩn 3S trên toàn quốc.</p><p>Đại lý Suzuki Vinh – Hà Tĩnh cũng được đưa vào hoạt động theo nhận diện và tiêu chuẩn cao nhất của Suzuki Việt Nam.</p></div></div><img src="/suzuki/about/showroom-interior.jpg" alt="Không gian trưng bày Suzuki Vinh" className="min-h-72 h-full w-full rounded-xl object-cover shadow-sm" /></section>
      <section className="mt-16 rounded-xl bg-[#eef2f6] p-7 md:p-10"><SectionHeading>2. Suzuki Vinh tự hào phân phối ô tô Suzuki Việt Nam</SectionHeading><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-5 leading-8 text-slate-700"><p>Suzuki Vinh là Đại lý chính thức của Suzuki Việt Nam tại Vinh, cung cấp xe với giá tốt, ưu đãi hấp dẫn và hỗ trợ trả góp đến 80% giá trị xe.</p><p>Các sản phẩm Suzuki được tin tưởng nhờ chất lượng bền bỉ, thiết kế thực dụng, hiệu quả kinh tế và phù hợp với nhu cầu sử dụng hằng ngày.</p><p className="font-semibold text-[#003b92]">“Những chiếc xe nhỏ cống hiến cho một tương lai lớn”.</p></div><div className="flex items-start gap-4 rounded-lg bg-white p-5 shadow-sm"><BadgeCheck className="shrink-0 text-[#ed1b2f]" size={34} /><p className="leading-7 text-slate-600">Sản phẩm chính hãng, tư vấn minh bạch, dịch vụ tận tâm và đồng hành cùng khách hàng trong suốt quá trình sử dụng xe.</p></div></div></section>
      <section className="mt-16"><SectionHeading>3. Sản phẩm ô tô Suzuki Vinh</SectionHeading><p className="max-w-3xl leading-8 text-slate-700">Suzuki Vinh kinh doanh, mua bán và cung cấp các dòng xe ô tô Suzuki chất lượng cao, bao gồm xe du lịch và xe thương mại.</p><div className="mt-7 grid gap-6 md:grid-cols-2"><Link href="/chi-tiet-xe" className="group relative min-h-64 overflow-hidden rounded-xl bg-[#003b92] p-7 text-white"><img src="/suzuki/about/suzuki-vinh.jpg" alt="Xe du lịch Suzuki" className="absolute inset-0 h-full w-full object-cover opacity-35 transition duration-500 group-hover:scale-105" /><div className="relative z-10 max-w-[58%]"><h3 className="suzuki-condensed text-2xl font-bold uppercase">Xe du lịch</h3><p className="mt-3 text-sm leading-6 text-white/85">Các dòng xe du lịch của Suzuki Vinh.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold">Khám phá <ArrowRight size={15} /></span></div></Link><Link href="/chi-tiet-xe" className="group relative min-h-64 overflow-hidden rounded-xl bg-[#172c48] p-7 text-white"><img src="/suzuki/about/service-workshop.jpg" alt="Xe thương mại Suzuki" className="absolute inset-0 h-full w-full object-cover opacity-35 transition duration-500 group-hover:scale-105" /><div className="relative z-10 max-w-[58%]"><h3 className="suzuki-condensed text-2xl font-bold uppercase">Xe thương mại</h3><p className="mt-3 text-sm leading-6 text-white/85">Các dòng xe thương mại phục vụ công việc.</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold">Khám phá <ArrowRight size={15} /></span></div></Link></div></section>
      <section className="mt-16 grid gap-10 border-t border-slate-200 pt-14 lg:grid-cols-[.9fr_1.1fr]"><img src="/suzuki/about/service-workshop.jpg" alt="Xưởng dịch vụ Suzuki Vinh" className="min-h-80 h-full w-full rounded-xl object-cover" /><div><SectionHeading>4. Dịch vụ sau bán hàng</SectionHeading><div className="space-y-5 leading-8 text-slate-700"><p>Suzuki Vinh cung cấp dịch vụ đóng thùng xe tải theo tiêu chuẩn và nhu cầu khách hàng; gia công, sửa chữa và đóng mới các loại thùng xe tải phù hợp quy định của Cục Đăng kiểm Việt Nam.</p><p>Xưởng dịch vụ rộng hơn 2.000m² với các khoang bảo dưỡng, sửa chữa và thiết bị đạt tiêu chuẩn quốc tế; phục vụ bảo hành, bảo dưỡng và sửa chữa nhanh chóng.</p><p>Cung cấp phụ tùng, phụ kiện chính hãng, cứu hộ xe 24/24 và dịch vụ đồng sơn với đội ngũ kỹ thuật viên giàu kinh nghiệm.</p><div className="flex items-start gap-3 rounded-lg border border-slate-200 bg-white p-4"><Wrench className="mt-1 shrink-0 text-[#ed1b2f]" size={22} /><p className="text-sm leading-6 text-slate-600">Suzuki Vinh phân phối sản phẩm và phục vụ khách hàng tại các huyện thuộc hai tỉnh Nghệ An và Hà Tĩnh.</p></div></div></div></section>
      <section className="mt-14 flex items-center gap-3 border-t border-slate-200 pt-7 text-sm text-slate-500"><CalendarDays size={16} className="text-[#ed1b2f]" />Suzuki Vinh – Đồng hành cùng khách hàng trên mọi hành trình.</section>
    </main>
  </PublicPageShell>;
}
