"use client";

import Image from "next/image";
import Link from "next/link";
import { ChevronDown, Mail, Menu, Phone, X } from "lucide-react";
import { useState } from "react";
import { usePathname } from "next/navigation";
import { usePublicSiteCars, type PublicNavCar } from "./public-site-cars-context";

function CarMegaMenu({ title, cars }: { title: string; cars: PublicNavCar[] }) {
  return <div className="pointer-events-none absolute inset-x-0 top-full z-50 hidden bg-white/95 px-4 py-3 shadow-[0_18px_32px_rgba(0,0,0,.18)] backdrop-blur-sm group-hover:pointer-events-auto group-hover:block group-focus-within:pointer-events-auto group-focus-within:block"><div className="mx-auto grid max-w-[1300px] grid-cols-2 gap-3 lg:grid-cols-4">{cars.map((car) => <Link key={car.slug || car.name} href={`/chi-tiet-xe/${car.slug || ""}`} className="group/car overflow-hidden rounded-xl border border-slate-100 bg-[#f2f3f6] text-center shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-28 bg-white p-2"><img src={car.img} alt={car.name} className="h-full w-full object-contain transition duration-300 group-hover/car:scale-105" /></div><div className="px-2 py-2"><h3 className="suzuki-condensed text-base font-bold uppercase text-[#171717]">{car.name}</h3><p className="suzuki-condensed mt-0.5 text-sm font-bold text-[#202020]">Chỉ từ: <span className="text-base text-[#ee1b2e]">{car.price}</span></p><span className="suzuki-condensed mt-2 inline-flex rounded-full bg-[#003b92] px-4 py-1 text-sm font-bold text-white">Xem chi tiết</span></div></Link>)}</div>{cars.length === 0 && <p className="mx-auto max-w-[1300px] py-3 text-center text-slate-500">{title} đang được cập nhật.</p>}</div>;
}

export function PublicHeader() {
  const pathname = usePathname() ?? "";
  const { currentCars, serviceCars, settings } = usePublicSiteCars();
  const [open, setOpen] = useState(false);
  const siteName = settings.site_name || "Suzuki Vinh Nghệ An";
  const phone = settings.phone_number || "0944 006 999";
  const email = settings.email || "suzukivinh.kinhdoanh@gmail.com";
  const address = settings.address || "Số 5B Đường Nguyễn Trãi - Tp.Vinh - Nghệ An";
  const zalo = settings.zalo_link || `https://zalo.me/${phone.replace(/\D/g, "")}`;
  const nav = [{ label: "Trang chủ", href: "/" }, { label: "Xe du lịch", href: "/chi-tiet-xe", cars: currentCars }, { label: "Xe thương mại", href: "/chi-tiet-xe", cars: serviceCars }, { label: "Về đại lý", href: "/ve-dai-ly" }, { label: "Bảng giá xe", href: "/chi-tiet-xe" }, { label: "Tin tức", href: "/su-kien" }, { label: "Liên hệ", href: "/lien-he" }, { label: "Công nghệ xe Suzuki", href: "/brochure" }];
  const socials = [{ name: "Facebook", src: "/logo/social/facebook.png", href: settings.facebook_link || "#" }, { name: "Zalo", src: "/logo/social/zalo.svg", href: zalo }, { name: "YouTube", src: "/logo/social/youtube.png", href: settings.youtube_link || "#" }, { name: "TikTok", src: "/logo/social/tiktok.png", href: settings.tiktok_link || "#" }];
  return <header className="relative z-50 bg-white shadow-sm">
    <div className="mx-auto flex h-[84px] max-w-[1300px] items-center px-3 sm:h-[62px] sm:px-4 lg:px-0"><Link href="/" className="relative z-10 flex h-[84px] w-[118px] shrink-0 items-center justify-center bg-white px-2 shadow-[0_3px_10px_rgba(0,0,0,.08)] sm:-mb-[46px] sm:h-[108px] sm:w-[138px] sm:px-3"><Image src="/logo/logosuzukifull.png" alt="Suzuki" fill sizes="(max-width: 639px) 118px, 138px" className="object-contain p-2 sm:p-3" /></Link><div className="ml-4 min-w-0 leading-tight"><p className="truncate text-[15px] font-bold uppercase tracking-wide text-[#ed1b2f] sm:text-[18px]">{siteName}</p><p className="mt-0.5 hidden text-[11px] font-semibold text-[#111b2b] sm:block">{address}</p></div><div className="ml-auto hidden items-center gap-4 lg:flex"><a href={`tel:${phone.replace(/\D/g, "")}`} className="flex items-center gap-1.5 text-[11px] leading-tight text-[#172033]"><Phone className="rounded bg-[#ed1b2f] p-1 text-white" size={22} fill="currentColor" /><span>Hotline:<br /><b className="text-[12px]">{phone}</b></span></a><a href={`mailto:${email}`} className="flex items-center gap-1.5 text-[11px] leading-tight text-[#172033]"><Mail className="rounded bg-[#ed1b2f] p-1 text-white" size={22} fill="currentColor" /><span>Email:<br /><b className="text-[12px]">{email}</b></span></a><div className="flex items-center gap-1.5">{socials.map((social) => <a key={social.name} href={social.href} aria-label={social.name} target="_blank" rel="noopener noreferrer"><Image src={social.src} alt={social.name} width={20} height={20} className="h-5 w-5 object-contain" /></a>)}</div></div></div>
    <nav className="relative bg-[#003b92] text-white"><div className="mx-auto hidden h-[46px] max-w-[1300px] items-stretch pl-[138px] lg:flex">{nav.map((item) => item.cars ? <div key={item.label} className="group static flex"><Link href={item.href} className={`suzuki-condensed flex items-center gap-1 px-4 text-[14px] font-extrabold uppercase transition hover:bg-[#ef2332] ${pathname === item.href ? "bg-[#ef2332]" : ""}`}>{item.label}<ChevronDown size={14} strokeWidth={3} /></Link><CarMegaMenu title={item.label} cars={item.cars} /></div> : <Link key={item.label} href={item.href} className={`suzuki-condensed flex items-center px-4 text-[14px] font-extrabold uppercase transition hover:bg-[#ef2332] ${pathname === item.href ? "bg-[#ef2332]" : ""}`}>{item.label}</Link>)}</div><button onClick={() => setOpen(!open)} className="flex h-[54px] w-full items-center justify-between px-5 text-left text-lg font-bold lg:hidden" aria-expanded={open}><span>Danh mục</span>{open ? <X size={34} /> : <Menu size={37} />}</button><div className={`${open ? "block" : "hidden"} border-t border-white/15 px-5 py-2 lg:hidden`}>{nav.map((item) => <div key={item.label}><Link onClick={() => setOpen(false)} href={item.href} className="block border-b border-white/15 py-3 text-sm font-bold uppercase">{item.label}</Link>{item.cars?.map((car) => <Link onClick={() => setOpen(false)} key={car.slug} href={`/chi-tiet-xe/${car.slug}`} className="block py-2 pl-4 text-sm text-white/80">{car.name}</Link>)}</div>)}</div></nav>
  </header>;
}
